/*-----------------------------------------------------------------------------
Hands-On Lab: Data Engineering with Snowpark
Script:       05_orders_update.sql
Author:       Jeremiah Hansen
Last Updated: 1/2/2023
-----------------------------------------------------------------------------*/

USE ROLE HOL_ROLE;
USE WAREHOUSE HOL_WH;
USE SCHEMA HOL_DB.HARMONIZED;


-- ----------------------------------------------------------------------------
-- Step #1: Create the orders table and streams if needed
-- ----------------------------------------------------------------------------

-- Debug: DROP TABLE ORDERS;

EXECUTE IMMEDIATE $$
BEGIN
  IF (EXISTS (SELECT * 
              FROM INFORMATION_SCHEMA.TABLES
              WHERE TABLE_SCHEMA = 'HARMONIZED'
                AND TABLE_NAME = 'ORDERS')) 
  THEN
    RETURN 'ORDERS table already exists.';
  ELSE
    CREATE TABLE IF NOT EXISTS ORDERS LIKE ORDERS_V;
    ALTER TABLE ORDERS ADD COLUMN META_UPDATED_AT TIMESTAMP;
    RETURN 'Created ORDERS table.';
  END IF;
END;
$$
;

-- Debug: DROP STREAM ORDERS_STREAM;
CREATE STREAM IF NOT EXISTS ORDERS_STREAM ON TABLE ORDERS
    SHOW_INITIAL_ROWS = TRUE;


-- ----------------------------------------------------------------------------
-- Step #3: Merge any changes from the stream to the target table
-- ----------------------------------------------------------------------------

-- Debug: SELECT * FROM ORDERS_V_STREAM LIMIT 100;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XLARGE;

MERGE INTO ORDERS AS TARGET
USING ORDERS_V_STREAM AS SOURCE
ON (TARGET.ORDER_DETAIL_ID = SOURCE.ORDER_DETAIL_ID)
WHEN MATCHED THEN UPDATE
SET
    TARGET.ORDER_ID = SOURCE.ORDER_ID,
    TARGET.TRUCK_ID = SOURCE.TRUCK_ID,
    TARGET.ORDER_TS = SOURCE.ORDER_TS,
    TARGET.ORDER_TS_DATE = SOURCE.ORDER_TS_DATE,
    TARGET.ORDER_DETAIL_ID = SOURCE.ORDER_DETAIL_ID,
    TARGET.LINE_NUMBER = SOURCE.LINE_NUMBER,
    TARGET.TRUCK_BRAND_NAME = SOURCE.TRUCK_BRAND_NAME,
    TARGET.MENU_TYPE = SOURCE.MENU_TYPE,
    TARGET.PRIMARY_CITY = SOURCE.PRIMARY_CITY,
    TARGET.REGION = SOURCE.REGION,
    TARGET.COUNTRY = SOURCE.COUNTRY,
    TARGET.FRANCHISE_FLAG = SOURCE.FRANCHISE_FLAG,
    TARGET.FRANCHISE_ID = SOURCE.FRANCHISE_ID,
    TARGET.FRANCHISEE_FIRST_NAME = SOURCE.FRANCHISEE_FIRST_NAME,
    TARGET.FRANCHISEE_LAST_NAME = SOURCE.FRANCHISEE_LAST_NAME,
    TARGET.LOCATION_ID = SOURCE.LOCATION_ID,
    TARGET.MENU_ITEM_ID = SOURCE.MENU_ITEM_ID,
    TARGET.MENU_ITEM_NAME = SOURCE.MENU_ITEM_NAME,
    TARGET.QUANTITY = SOURCE.QUANTITY,
    TARGET.UNIT_PRICE = SOURCE.UNIT_PRICE,
    TARGET.PRICE = SOURCE.PRICE,
    TARGET.ORDER_AMOUNT = SOURCE.ORDER_AMOUNT,
    TARGET.ORDER_TAX_AMOUNT = SOURCE.ORDER_TAX_AMOUNT,
    TARGET.ORDER_DISCOUNT_AMOUNT = SOURCE.ORDER_DISCOUNT_AMOUNT,
    TARGET.ORDER_TOTAL = SOURCE.ORDER_TOTAL,
    TARGET.META_UPDATED_AT = TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP())
WHEN NOT MATCHED THEN INSERT
(
    ORDER_ID,
    TRUCK_ID,
    ORDER_TS,
    ORDER_TS_DATE,
    ORDER_DETAIL_ID,
    LINE_NUMBER,
    TRUCK_BRAND_NAME,
    MENU_TYPE,
    PRIMARY_CITY,
    REGION,
    COUNTRY,
    FRANCHISE_FLAG,
    FRANCHISE_ID,
    FRANCHISEE_FIRST_NAME,
    FRANCHISEE_LAST_NAME,
    LOCATION_ID,
    MENU_ITEM_ID,
    MENU_ITEM_NAME,
    QUANTITY,
    UNIT_PRICE,
    PRICE,
    ORDER_AMOUNT,
    ORDER_TAX_AMOUNT,
    ORDER_DISCOUNT_AMOUNT,
    ORDER_TOTAL,
    META_UPDATED_AT
)
VALUES
(
    SOURCE.ORDER_ID,
    SOURCE.TRUCK_ID,
    SOURCE.ORDER_TS,
    SOURCE.ORDER_TS_DATE,
    SOURCE.ORDER_DETAIL_ID,
    SOURCE.LINE_NUMBER,
    SOURCE.TRUCK_BRAND_NAME,
    SOURCE.MENU_TYPE,
    SOURCE.PRIMARY_CITY,
    SOURCE.REGION,
    SOURCE.COUNTRY,
    SOURCE.FRANCHISE_FLAG,
    SOURCE.FRANCHISE_ID,
    SOURCE.FRANCHISEE_FIRST_NAME,
    SOURCE.FRANCHISEE_LAST_NAME,
    SOURCE.LOCATION_ID,
    SOURCE.MENU_ITEM_ID,
    SOURCE.MENU_ITEM_NAME,
    SOURCE.QUANTITY,
    SOURCE.UNIT_PRICE,
    SOURCE.PRICE,
    SOURCE.ORDER_AMOUNT,
    SOURCE.ORDER_TAX_AMOUNT,
    SOURCE.ORDER_DISCOUNT_AMOUNT,
    SOURCE.ORDER_TOTAL,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP())
);

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XSMALL;

-- Debug: SELECT * FROM ORDERS_V_STREAM LIMIT 100;
-- Debug: SELECT * FROM ORDERS LIMIT 100;
